### ISSUE TITLE
print function generalization

### ISSUE THREAD

**Issue by kaprakashr** [kaprakashr/Frooty#22]
1. print(log, "This is" , name) 
    >> This is KALYANA PRAKASH
2. print(log, "SUCCESS", "test case is passing", "parameters: ", var1, var2)
    >> SUCCESS test case is passing parameters: 10, 11

print(log, followed by any number strings)

search for: function with any number of parameters

**Comment by sa-ku** [comment]
This feature is already available, for reference 
Here is an example

var1 = 1
var2 = 2

Print("the value of var1 is : %d and var2 is : %d : PASSED" % (var1 , var2) ,log)

output:-
[03:16:01]: the value of var1 is : 1 and var2 is : 2 : PASSED
