### ISSUE TITLE
New Summary file format

### ISSUE THREAD

**Issue by kaprakashr** [kaprakashr/Frooty#27]
#-------------------------------------------------#
          FROOTY AUTOMATION ENVIRONMENT            
#-------------------------------------------------#
WebLink For results: <>
Result Exported to DB: NO
**Test Start Time: <DD/MM/YY HH:MM:SS>**
**Test Run ID: <RANDOM GENERATED 6 DIGIT UNIQUE ID>**
**Test Run Time: <TEST RUN TIME>**
**Test Batch Name: <BATCH FILE NAME>**
**Test Topology Name: <TOPOLOGY FILE NAME>**
**Features: <ALL INDIVIDUAL file names inside BATCH FILES, separated by comma>**

#-------TEST CASE STATISTICS------------
TOTAL TEST CASES EXECUTED : 6
TOTAL TEST CASES PASSED   : 6
TOTAL TEST CASES FAILED   : 0
TOTAL TEST CASES BLOCKED  : 1

SUCCESS RATE : 100%

#-------TEST RUN METRICS----------------
**FEATURE<<>>TESTCASE NAME <<>> RESULT<<>>RUN TIME

snmp_example_walk<<>>TEST_CASE_001<<>>PASS<<>>00:00:01
snmp_example_walk<<>>TEST_CASE_002<<>>PASS<<>>00:00:01
snmp_example_get<<>>TEST_CASE_001<<>>PASS<<>>0:00:00**

**#-------Diagnostics of Individual Tests------
#-------LOGS---------
snmp_example_walk<<>>/root/saroj/TEST/Batch_Feature/Frooty/LOGS/SMOKE_SANITY_2017-11-050248/snmp_example_walk_TEST_CASE_001_2017-11-05_02:48:10.log
snmp_example_walk<<>>/root/saroj/TEST/Batch_Feature/Frooty/LOGS/SMOKE_SANITY_2017-11-050248/snmp_example_walk_TEST_CASE_002_2017-11-05_02:48:10.log**

#-------Topology Details----------
{"DEVICE_1": {"username": "abc123", "name": "dut", "ip": "127.0.0.1", "snmp_port": "161", "mode": "telnet", "password": "abc123", "port": "23", "community_string": "public"}}

**Comment by sa-ku** [comment]
new file format code is completed and merged to https://github.com/kaprakashr/Frooty/blob/master/Frooty_Batch.py
